export const COUNTRY_CODES = [
  { code: "+52", country: "MX", label: "MX (+52)" },
  { code: "+1", country: "US", label: "US (+1)" },
  { code: "+1", country: "CA", label: "CA (+1)" },
  { code: "+54", country: "AR", label: "AR (+54)" },
  { code: "+55", country: "BR", label: "BR (+55)" },
  { code: "+56", country: "CL", label: "CL (+56)" },
  { code: "+57", country: "CO", label: "CO (+57)" },
  { code: "+506", country: "CR", label: "CR (+506)" },
  { code: "+53", country: "CU", label: "CU (+53)" },
  { code: "+593", country: "EC", label: "EC (+593)" },
  { code: "+503", country: "SV", label: "SV (+503)" },
  { code: "+502", country: "GT", label: "GT (+502)" },
  { code: "+504", country: "HN", label: "HN (+504)" },
  { code: "+505", country: "NI", label: "NI (+505)" },
  { code: "+507", country: "PA", label: "PA (+507)" },
  { code: "+595", country: "PY", label: "PY (+595)" },
  { code: "+51", country: "PE", label: "PE (+51)" },
  { code: "+1809", country: "DO", label: "DO (+1809)" },
  { code: "+598", country: "UY", label: "UY (+598)" },
  { code: "+58", country: "VE", label: "VE (+58)" },
] as const
