export const COUNTRY_CODES = [
  { code: "+52", country: "MX", flag: "🇲🇽", label: "🇲🇽 MX (+52)" },
  { code: "+1", country: "US", flag: "🇺🇸", label: "🇺🇸 US (+1)" },
  { code: "+1", country: "CA", flag: "🇨🇦", label: "🇨🇦 CA (+1)" },
  { code: "+54", country: "AR", flag: "🇦🇷", label: "🇦🇷 AR (+54)" },
  { code: "+55", country: "BR", flag: "🇧🇷", label: "🇧🇷 BR (+55)" },
  { code: "+56", country: "CL", flag: "🇨🇱", label: "🇨🇱 CL (+56)" },
  { code: "+57", country: "CO", flag: "🇨🇴", label: "🇨🇴 CO (+57)" },
  { code: "+506", country: "CR", flag: "🇨🇷", label: "🇨🇷 CR (+506)" },
  { code: "+53", country: "CU", flag: "🇨🇺", label: "🇨🇺 CU (+53)" },
  { code: "+593", country: "EC", flag: "🇪🇨", label: "🇪🇨 EC (+593)" },
  { code: "+503", country: "SV", flag: "🇸🇻", label: "🇸🇻 SV (+503)" },
  { code: "+502", country: "GT", flag: "🇬🇹", label: "🇬🇹 GT (+502)" },
  { code: "+504", country: "HN", flag: "🇭🇳", label: "🇭🇳 HN (+504)" },
  { code: "+505", country: "NI", flag: "🇳🇮", label: "🇳🇮 NI (+505)" },
  { code: "+507", country: "PA", flag: "🇵🇦", label: "🇵🇦 PA (+507)" },
  { code: "+595", country: "PY", flag: "🇵🇾", label: "🇵🇾 PY (+595)" },
  { code: "+51", country: "PE", flag: "🇵🇪", label: "🇵🇪 PE (+51)" },
  { code: "+1809", country: "DO", flag: "🇩🇴", label: "🇩🇴 DO (+1809)" },
  { code: "+598", country: "UY", flag: "🇺🇾", label: "🇺🇾 UY (+598)" },
  { code: "+58", country: "VE", flag: "🇻🇪", label: "🇻🇪 VE (+58)" },
] as const
